on:
  push:
    branches:
    - main
    - release/*
jobs:
  my_job:
    name: hola dese git
    runs-on: ubuntu-22.04
    steps:
      - name: Test Action Hola
        run: echo "hola desde github actions"
        
